### PR TITLE
feat: `paginatingEndpoints` and `isPaginatingEndpoint`

### PR DESCRIPTION
**Pull request by ptomulik**
The ``isPaginatingEndpoint`` function provides a runtime type-guard for ``keyof PaginatingEndpoint``. The PR also exposes ``paginatingEndpoints`` array that lists all the keys in the generated ``PaginatingEndpoints`` interface.

### CODE REVIEW

**Review by gr2m — CHANGES_REQUESTED** [review]
Can you add tests for the new exports to https://github.com/octokit/plugin-paginate-rest.js/blob/master/test/smoke.test.ts?

As this adds features, we should update the docs.

Can you add the new exports to the imports in https://github.com/octokit/plugin-paginate-rest.js/tree/42df25d3ccfcdb27194032d6a77d2495af085a6a#usage and add sections for each export to the doc?

**Comment by ptomulik** [comment]
> Can you add tests for the new exports to https://github.com/octokit/plugin-paginate-rest.js/blob/master/test/smoke.test.ts?
> 

Tests are already in [test/paginating-endpoints.test.ts](https://github.com/octokit/plugin-paginate-rest.js/pull/283/files#diff-e0124445c28b984f7f4e184f6e2fed43e1f8ac84a8589e379f46e99a81552fa8). Anything specific that should be additionally tested in smoke.test.ts?

> As this adds features, we should update the docs.
> 
> Can you add the new exports to the imports in https://github.com/octokit/plugin-paginate-rest.js/tree/42df25d3ccfcdb27194032d6a77d2495af085a6a#usage and add sections for each export to the doc?

Sure.

**Comment by gr2m** [comment]
> Anything specific that should be additionally tested in smoke.test.ts?

I just like to test all exports of a module in the smoke test. Only import the function and the array and check that they are a function/array respectively. It's just an additional safety measure to avoid accidental breaking changes

**Review by gr2m — APPROVED** [review]
Thanks!

**Pull request merged**
