### PR TITLE
fix(package): add `@octokit/core` as peer dependency

### LINKED ISSUE #124: [yarn 2] Cannot find module '@octokit/core' or its corresponding type declarations
While consuming this package in yarn v2, I got a compile break because this package consumes `@octokit/core` at runtime:

https://github.com/octokit/plugin-paginate-rest.js/blob/fb3e08dfba3a403346bd3ca45c6820c8c3dac00f/src/index.ts#L8

Yet is package.json file claims that this dependency is not needed in production:

https://github.com/octokit/plugin-paginate-rest.js/blob/fb3e08dfba3a403346bd3ca45c6820c8c3dac00f/package.json#L27-L31

Yarn's PnP mode catches this error, and I have to workaround it by putting it into [loose mode](https://yarnpkg.com/features/pnp/#pnp-loose-mode).

### PR DESCRIPTION
**Pull request by gr2m**
fixes #124

### CODE REVIEW

**Comment by gr2m** [comment]
@AArnot you can test this PR by doing the yarn counterpart of `npm install https://github.pika.dev/octokit/plugin-paginate-rest.js/pr/130`

**Comment by AArnott** [comment]
Yes, I'll test this out and if it doesn't work I'll give you repro steps. My GitHub username ends with two "t"s by the way, so you mentioned someone else.

**Comment by timocov** [comment]
This fix just dropped support for packages/libraries with TypeScript below 3.8 version... Is there a difference between using `import` and `import type` here? Why can't we use just `import` instead?

**Comment by timocov** [comment]
@gr2m I mean, this was released as a patch release, but contains breaking changes. Is that okay?

**Comment by gr2m** [comment]
My understanding is that `import type` will make sure that no code will be imported into the final code. I don't consider TypeScript changes breaking changes because you don't use it in production, only in development. TypeScript itself does not follow semver with its releases.

Is there a reason you are stuck with TypeScript below 3.8?

**Comment by timocov** [comment]
> Is there a reason you are stuck with TypeScript below 3.8?

Some of our branches are still on 3.7. Is that really problem and too outdated? I don't think so. It's just around 1yo version though 😂 

> My understanding is that import type will make sure that no code will be imported into the final code

The same as `import` if you'll use imported reference as type and in types only. So if you don't use it anywhere else from types, they are completely the same. But in d.ts files (which you provide with the npm package to consumers) they are always the same, because d.ts is used for the type checking stage only (d.ts files doesn't produce any output).

> I don't consider TypeScript changes breaking changes because you don't use it in production, only in development

But this changes might accidentally break any build (development as well) without any reason, just because there is the new _patch_ version of the library, and if you don't use lock files (there might be some reasons why you don't/can't use them) you'll have "happy morning" by fixing compilation errors, even if you didn't do any change in your code.

> TypeScript itself does not follow semver with its releases.

And you? I don't think that versioning of this package is related to TypeScript's versioning system.

This looks similar to if you published the new boost/Qt patch version of the library and have started to use new features from the new C++ standard. I believe in this case it should be the new major version at least to avoid confusing and inconvenience.

**Comment by timocov** [comment]
@gr2m I don't say that you don't need to use features from the new TypeScript version, but if someone has consumers, they should worry about it. In this case, my personal opinion that using `import type` isn't necessary, but if you decided to use it - please bump a major version instead to avoid breaking code. Or declare that all libraries doesn't follow semver (but I guess it requires more changes, because they need to change `dependencies` and `devDependencies` lists). Please don't get me wrong.

**Comment by gr2m** [comment]
can you send a PR to change the `import type` to just `import`?

**Comment by timocov** [comment]
Sure https://github.com/octokit/plugin-paginate-rest.js/pull/160

**Review by Shahid439-max — COMMENTED** [review]
run kit

**Pull request merged**
